export const PATH = {
  HOME: '/',
  LOGIN: '/login',
  ENROLL: '/enroll',
  PROFILE: '/profile',
  MY_PAGE: '/my-dashboard',
  TEAMS: '/team-list',
  TEAM_REGISTRATION: '/team-registration',
  TEAM_SETTING: '/team-setting',
  TEAM_DASHBOARD: '/team-dashboard',
  TEAM_ADMIN: '/team-admin',
  SUBJECT: '/team-subject/:id/:selectedDate',
  POSTING: '/posting/:id',
  TEAM_RECRUIT: '/team-recruit',
};
